[project]
name = "crt"
version = "0.1.0"
description = ""
authors = [
    {name = "Erik Leclercq",email = "rkleclercq@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightglue @ git+https://github.com/cvg/LightGlue.git",
    "json5 (>=0.12.1,<0.13.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "numpy (>=2.3.3,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "ffmpeg (>=1.4,<2.0)",
    "jsonschema (>=4.25.1,<5.0.0)",
    "muDIC @ git+https://github.com/PolymerGuy/muDIC.git",
    "torch (>=2.8.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
